sudo: false
dist: trusty
language: python
python:
  - "2.7"
notifications:
  email: false
install:
    - pip install coveralls
    - pip install -r dev_requirements.txt
script:
    ./build
after_success:
    coveralls
